language: csharp

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
#  removed   

addons:
  coverity_scan:
    project:
      name: "IMA-DZ/WhiteCore-Dev"
      description: "Build submitted via Travis CI"
    notification_email: dz@opensimian.com
    build_command_prepend: "./runprebuild.sh -c Debug -a x64 -b Yes"
    build_command:   "xbuild"
    branch_pattern: master
    
mono:
  - latest
script:
  - ./runprebuild.sh -c Debug -a x64 -b Yes

sudo: false
